### ISSUE TITLE
Add sortType/searchType support for every column

### ISSUE THREAD

**Issue by dimitargenov** [raketasoft/ng2-grid#15]
Currently the grid searches and sorts all the columns as strings. Maybe it should be nice to have option sortType or searchType for example number/string

**Comment by branimirborisov** [comment]
Fixed with latest commit (https://github.com/raketasoft/ng2-grid/commit/2bb629115e33629034f7beaeea9dcfbbc4a66307), support is added for "number" column type, which would result in corresponding behavior during filtering, sorting and validation.
