### ISSUE TITLE
Add possibility to specify filterChangedCallback

### ISSUE THREAD

**Issue by Vitaliy-Svinchyak** [raketasoft/ng2-grid#17]
In callback will be needed the name of the filter and it's new value

**Comment by branimirborisov** [comment]
Instead for filter change callback now the grid would trigger some output events during filter change, sort change, page change, results update & etc. Event support is added with this commit https://github.com/raketasoft/ng2-grid/commit/d7b1a0df105727488e8782974e108ced1503e390

Full list of supported events and the GridEvent object emitted during each event can be found in the Full Configuration Example on the Demo page: https://github.com/raketasoft/ng2-grid/blob/master/demo/demo.component.html#L87

The new GridEvent class could be found here: https://github.com/raketasoft/ng2-grid/blob/master/src/grid-event.ts

If you think this covers the issue let me know so I can close it.

**Comment by Vitaliy-Svinchyak** [comment]
Yes, it covers my issue. Thanks
