### ISSUE TITLE
Uncaught No Directive annotation found on GridComponent

### ISSUE THREAD

**Issue by nilsenj** [raketasoft/ng2-grid#4]
Hello. New version of angular 2.0.5 doesn't support it.
I've installed "raketasoft-ng2-grid": "^1.0.0-alpha.10",
and it throws

error: Uncaught No Directive annotation found on GridComponent

**Comment by branimirborisov** [comment]
Hi, Thanks for feedback. I'll try releasing 2.0.5 compatible version in next few days.

**Comment by branimirborisov** [comment]
An update has been released supporting Angular 2.4.0.
